#!/usr/bin/env python3

import os.path as p, sys
from PyQt5.QtWidgets import QApplication, QDialog, QFileDialog


app = QApplication(sys.argv)

#dlg = QDialog()
#dlg.exec()

dlg = QFileDialog(
        caption='Please choose a file with DNA',
        directory=p.normpath(p.join(p.dirname(sys.argv[0]), '..', 'DNA')))
dlg.exec()
